services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/src/app
    environment:
      - NODE_ENV=development
    command: npm run dev
